[package]
name = "migrator"
version.workspace = true
edition.workspace = true

[dependencies]
dotenvy = { git = "https://github.com/allan2/dotenvy", rev = "86c0d6dd2938e615135813df9e3274bf8f42c455", features = ["macros"]}
migration = { path = "../migration" }
sea-orm = { version = "2.0.0-rc", features = [ "sqlx-postgres", "runtime-tokio", "macros", "with-uuid" ] }
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread", "rt"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["fmt", "env-filter"] }