[package]
name = "api"
version.workspace = true
edition.workspace = true

[dependencies]
schema = { path = "../schema" }
utilities = { path = "../utilities" }
dotenvy = { git = "https://github.com/allan2/dotenvy", rev = "fa25166994d6978bd2e002f0ed190c0c39674ebe", features = ["macros"]}
axum = { version = "0.8.6", features = ["macros"] }
sea-orm = { version = "2.0.0-rc", features = [ "sqlx-postgres", "runtime-tokio-rustls", "runtime-tokio", "macros", "with-uuid" ] }
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
anyhow = "1.0.100"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["fmt", "env-filter"] }
tower-http = { version = "0.7.0", features = ["trace"] }
serde = "1.0.228"
utoipa = { version = "5.4.0", features = ["axum_extras"] }
utoipa-axum = "0.2.0"
utoipa-scalar = { version = "0.3.0", features = ["axum"] }
validator = { version = "0.21.0", features = ["derive"] }
