name: Build Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: dtolnay/rust-toolchain@4cda84d5c5c54efe2404f9d843567869ab1699d4 # stable
      - run: cargo build
